# Generated by Django 3.0.3 on 2020-03-03 00:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200302_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alias',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 0, 25, 16, 129149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 0, 25, 16, 128152, tzinfo=utc)),
        ),
    ]
